{{- if .Values.rbac.create }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ template "gate.fullname" . }}
  labels:
    app: {{ template "gate.fullname" . }}
    charts: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: [""]
  verbs: [""]
{{- end }}
