apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "gate.fullname" . }}
    charts: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
{{ toYaml .Values.secret.annotations | indent 4 }}
type: Opaque
data:
  gateOauthClientId: {{ .Values.config.gateOauthClientID | b64enc | quote }}
  gateOauthClientSecret: {{ .Values.config.gateOauthClientSecret | b64enc | quote }}
  gateDBHost: {{ .Values.config.gateDBHost | b64enc | quote }}
  gateDBPort: {{ .Values.config.gateDBPort | b64enc | quote }}
  gateDBName: {{ .Values.config.gateDBName | b64enc | quote }}
  gateDBUser: {{ .Values.config.gateDBUser | b64enc | quote }}
  gateDBPassword: {{ .Values.config.gateDBPassword | b64enc | quote }}
  cacheHost: {{ .Values.config.cacheHost | b64enc | quote }}
  cachePort: {{ .Values.config.cachePort | b64enc | quote }}
  secretKeyBase: {{ .Values.config.secretKeyBase | b64enc | quote }}
  secretApiKey: {{ .Values.config.secretApiKey | b64enc | quote }}
  gateConfigSecret: {{ .Values.config.gateConfigSecret | b64enc | quote }}
  gateVpnSslCert: {{ .Values.config.gateVpnSslCert | b64enc | quote }}
  gateVpnSslXsigned: {{ .Values.config.gateVpnSslXsigned | b64enc | quote }}
  gateVpnSslPrivateKey: {{ .Values.config.gateVpnSslPrivateKey | b64enc | quote }}
  newrelicLicenseKey: {{ .Values.config.newrelicLicenseKey | b64enc | quote }}
