apiVersion: v1
kind: Service
metadata:
  name: {{ template "gate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "gate.fullname" . }}
    charts: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations: 
    {{- if .Values.service.annotations -}}
    {{ toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{ template "gate.fullname" . }}
  type: {{ .Values.service.type }}
  {{- if (and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if (and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerSourceRanges))) }}
  loadBalancerSourceRanges: 
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - name: gate
      port: {{ .Values.service.port }}
      targetPort: gate
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
