{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "rbac.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "gate.fullname" . }}
    charts: {{ .Chart.Name }}-{{ .Chart.Version }}
{{- end }}
