language: generic
os: linux

install:
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
script:
  - helm lint */.

before_deploy:
  - helm package -d /tmp/dist/packs */.
  - git fetch origin gh-pages:gh-pages
  - git read-tree $(git rev-parse gh-pages)
  - git checkout-index -af --prefix /tmp/dist/to-be-deployed/
  - >
    for f in $(git ls-tree -r -t --full-name --name-only gh-pages) ; do
      touch -t $(git log --pretty=format:%cI -1 gh-pages -- "$f") "/tmp/dist/to-be-deployed/$f";
    done
  - mv -vn /tmp/dist/packs/* /tmp/dist/to-be-deployed
  - helm repo index /tmp/dist/to-be-deployed
deploy:
  provider: pages
  token: $GITHUB_TOKEN

  local_dir: /tmp/dist/to-be-deployed
  keep_history: true
  on:
    branch: master
