language: generic
os: linux

install:
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
script:
  - helm lint */.

before_deploy:
  - helm package -d /tmp/dist/packs */.
  - mkdir -p /tmp/dist/deploy
  - >
    if git fetch origin gh-pages:gh-pages; then
      echo OK1
      git read-tree $(git rev-parse gh-pages)
      echo OK2
      git checkout-index -af --prefix /tmp/dist/deploy/
      echo OK3
      for f in /tmp/dist/packs/*; do
        echo OK $f
        [ -f "/tmp/dist/deploy/$(basename "$f")" ] && rm "$f"
      done
    fi
  - helm repo index --url "https://nieltg.github.io/helm-chart-experiment" --merge /tmp/dist/deploy/index.yaml /tmp/dist/packs
  - mv -v /tmp/dist/packs/* /tmp/dist/deploy
deploy:
  provider: pages
  token: $GITHUB_TOKEN

  local_dir: /tmp/dist/deploy
  keep_history: true
  on:
    branch: master
